spring:
  application:
    name: ai-demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:ai}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
  ai:
    openai:
      base-url: https://xxx.xxx.xxx
      api-key: sk-xxxxxx
      chat:
        options:
          model: gpt-4o
    anthropic:
      base-url: https://xxx.xxx.xxx
      api-key: sk-xxxxxx
